### 
GET http://localhost:5000/api/users/all

### 
DELETE  http://localhost:5000/api/users/5/delete


### 
DELETE  http://localhost:5000/api/users/5/suspend



### register user
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "Username": "leo",
  "Email": "leo@exa.com",
  "Password": "password1",
  "isAdmin": true
}

### Login user
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
  "Email": "user@exa.com",
  "Password": "password1"
}

### Login user
PUT http://localhost:5000/api/users/:UserID/update
Content-Type: application/json
{
  "Username": "updated_user",
  "Balance": 500.00
}

### Login user
PUT http://localhost:5000/api/users/:UserID/updatePassword
Content-Type: application/json
{
  "Password": "newpassword123"
}

GET http://localhost:5000/api/users/:UserID

### 
POST http://localhost:5000/api/create
Content-Type: application/json

{
    "SenderID": 2, 
    "ReceiverID": 4, 
    "Amount": 100
}

###
GET http://localhost:5000/api/all/transactions



###
POST http://localhost:5000/api/create/payment
Content-Type: application/json

{
    "UserID": 1,
    "MerchantID": 4,
    "Amount": 50.00,
    "Currency": "USD",
    "PaymentGateway": "plisio",
    "PaymentStatus": "Success"
 }


###
GET http://localhost:5000/api/all/payments


###
POST http://localhost:5000/api/create/grant
Content-Type: application/json

{
    "GrantorID": 2,
    "GranteeID": 3,
    "Privilege": "admin",
    "GrantAmount": 179.00
}

###
GET http://localhost:5000/api/all/grants


###
GET http://localhost:5000/api/grant/3


###
GET http://localhost:5000/api/

###
POST http://localhost:5000/api/create/referrals
Content-Type: application/json

{
  "referrerID": 2,
  "referralCode": "AJX124",
  "referredID": 4
}


###
PUT http://localhost:5000/api/update/referrals
Content-Type: application/json

{
    "referralCode": "AHC124",
    "referredID": 2
}


###
GET http://localhost:5000/api/referrals/ABC123

###
GET http://localhost:5000/api/all/referrals


###
GET http://localhost:5000/api/referrals/user/2

